### ISSUE TITLE
Failed to open stream warning generated when default-properties.yml doesn't exist

### ISSUE THREAD

**Issue by piotrkwiecinski** [staempfli/universal-code-generator#2]
Running `mg2-codegen config:display` before `mg2-codegen config:set` generates a warning below:

```
Display Configuration
PHP Warning:  file_get_contents(/home/xx/.mg2-codegen/config/default-properties.yml): failed to open stream: No such file or directory in /home/xx/.composer/vendor/staempfli/universal-code-generator/src/Staempfli/UniversalGenerator/Tasks/PropertiesTask.php on line 145
PHP Stack trace:
PHP   1. {main}() /home/xx/.composer/vendor/staempfli/magento2-code-generator/bin/mg2-codegen:0
PHP   2. Staempfli\UniversalGenerator\Application->run() /home/xx/.composer/vendor/staempfli/magento2-code-generator/bin/mg2-codegen:31
PHP   3. Staempfli\UniversalGenerator\Application->run() /home/xx/.composer/vendor/staempfli/universal-code-generator/src/Staempfli/UniversalGenerator/Application.php:69
PHP   4. Staempfli\UniversalGenerator\Application->doRun() /home/xx/.composer/vendor/symfony/console/Application.php:148
PHP   5. Staempfli\UniversalGenerator\Application->doRunCommand() /home/xx/.composer/vendor/symfony/console/Application.php:248
PHP   6. Staempfli\UniversalGenerator\Command\Config\ConfigDisplayCommand->run() /home/xx/.composer/vendor/symfony/console/Application.php:953
PHP   7. Staempfli\UniversalGenerator\Command\Config\ConfigDisplayCommand->run() /home/xx/.composer/vendor/staempfli/universal-code-generator/src/Staempfli/UniversalGenerator/Command/AbstractCommand.php:32
PHP   8. Staempfli\UniversalGenerator\Command\Config\ConfigDisplayCommand->execute() /home/xx/.composer/vendor/symfony/console/Command/Command.php:255
PHP   9. Staempfli\UniversalGenerator\Tasks\PropertiesTask->loadDefaultProperties() /home/xx/.composer/vendor/staempfli/universal-code-generator/src/Staempfli/UniversalGenerator/Command/Config/ConfigDisplayCommand.php:30
PHP  10. file_get_contents() /home/xx/.composer/vendor/staempfli/universal-code-generator/src/Staempfli/UniversalGenerator/Tasks/PropertiesTask.php:145
PHP Fatal error:  Uncaught TypeError: Argument 1 passed to Staempfli\UniversalGenerator\Tasks\PropertiesTask::addProperties() must be of the type array, null given, called in /home/xx/.composer/vendor/staempfli/universal-code-generator/src/Staempfli/UniversalGenerator/Tasks/PropertiesTask.php on line 146 and defined in /home/xx/.composer/vendor/staempfli/universal-code-generator/src/Staempfli/UniversalGenerator/Tasks/PropertiesTask.php:75
Stack trace:
#0 /home/xx/.composer/vendor/staempfli/universal-code-generator/src/Staempfli/UniversalGenerator/Tasks/PropertiesTask.php(146): Staempfli\UniversalGenerator\Tasks\PropertiesTask->addProperties(NULL)
#1 /home/xx/.composer/vendor/staempfli/universal-code-generator/src/Staempfli/UniversalGenerator/Command/Config/ConfigDisplayCommand.php(30): Staempfli\UniversalGenerator\Tasks\PropertiesTask->loadDefaultProperties()
#2 /home/xx/.composer/vendor/symfony/console/Command/Command.php(255): Staempfli\UniversalGenerator\Command\Config\ConfigDisplayCommand->execute(Object(Sym in /home/xx/.composer/vendor/staempfli/universal-code-generator/src/Staempfli/UniversalGenerator/Tasks/PropertiesTask.php on line 75
```

**Comment by piotrkwiecinski** [comment]
Closing as it was merged
